; Generate bytecode that prints "Hello from Lisp-generated bytecode!"

(defun append (lst1 lst2)
  (if (== lst1 '())
    lst2
    (cons (car lst1) (append (cdr lst1) lst2))))

(defun u32-to-bytes (n)
  (cons (% n 256)
    (cons (% (/ n 256) 256)
      (cons (% (/ n 65536) 256)
        (cons (/ n 16777216) '())))))

; Bytecode file structure:
;   Header: "LISP" + version
;   Function count: 0
;   Main bytecode count: 3
;   Instruction 1: Push string
;   Instruction 2: Print
;   Instruction 3: Halt

(defun make-bytecode ()
  (let ((header '(76 73 83 80 6)))           ; "LISP" version 6
  (let ((func-count (u32-to-bytes 0)))       ; 0 functions
  (let ((main-count (u32-to-bytes 3)))       ; 3 instructions
  (let ((push-str (make-push-string)))       ; Push "Hello from Lisp-generated bytecode!"
  (let ((print-instr '(11)))                 ; Print opcode
  (let ((halt-instr '(12)))                  ; Halt opcode
    (append header
      (append func-count
        (append main-count
          (append push-str
            (append print-instr halt-instr))))))))))))

; Create Push instruction for string value
; Opcode 0 = Push
; Value tag 4 = String
; Then u32 length + ASCII bytes
(defun make-push-string ()
  (let ((opcode '(0)))           ; Push instruction
  (let ((value-tag '(4)))        ; String value tag
  (let ((str-len (u32-to-bytes 38)))  ; Length of message
  (let ((str-bytes '(72 101 108 108 111 32 102 114 111 109 32 76 105 115 112 45 103 101 110 101 114 97 116 101 100 32 98 121 116 101 99 111 100 101 33)))
    (append opcode
      (append value-tag
        (append str-len str-bytes))))))))

(defun main ()
  (let ((bytecode (make-bytecode)))
    (if (write-binary-file "/tmp/hello-from-lisp.bc" bytecode)
      (print "SUCCESS! Run: ./lisp-vm /tmp/hello-from-lisp.bc")
      (print "Failed to write bytecode"))))

(main)
