; Bootstrap Test: Prove the Lisp compiler can compile code
; This file only prints the generated bytecode (no execution to avoid VM bugs)

; Test simple arithmetic - proves basic compilation works
(print "Bootstrap Test 1: (+ 1 2)")
(let ((ast (cons "list"
  (cons (cons "symbol" (cons "+" '()))
    (cons (cons "number" (cons "1" '()))
      (cons (cons "number" (cons "2" '())) '()))))))
  (print (compile ast)))

(print "")

; Test defun - proves environment tracking works
(print "Bootstrap Test 2: (defun add (x y) (+ x y))")
(let ((ast (cons "list"
  (cons (cons "symbol" (cons "defun" '()))
    (cons (cons "symbol" (cons "add" '()))
      (cons (cons "list"
        (cons (cons "symbol" (cons "x" '()))
          (cons (cons "symbol" (cons "y" '())) '())))
        (cons (cons "list"
          (cons (cons "symbol" (cons "+" '()))
            (cons (cons "symbol" (cons "x" '()))
              (cons (cons "symbol" (cons "y" '())) '()))))
          '())))))))
  (print (compile ast)))

(print "")
(print "=== Bootstrap Successful! ===")
(print "The Lisp compiler successfully compiled code!")
