(defun make-env ()
  '((bytecode . ())
    (functions . ())
    (param-names . ())
    (local-bindings . ())))

(defun env-get (env key)
  (cdr (assoc-lookup key env)))

(defun assoc-lookup
  ((key '()) '())
  ((key ((k . v) . rest))
    (if (== k key)
      (cons k v)
      (assoc-lookup key rest))))

(defun env-set (env key value)
  (cons (cons key value)
        (filter (lambda (pair) (not (== (car pair) key))) env)))

(defun compile-literal (value env)
  (cons env (list (list 'push value))))

(defun compile-add (a b env)
  (let ((ra (compile-expr a env)))
    (let ((env1 (car ra)))
      (let ((bca (cdr ra)))
        (let ((rb (compile-expr b env1)))
          (let ((env2 (car rb)))
            (let ((bcb (cdr rb)))
              (cons env2 (append bca (append bcb '((add))))))))))))

(defun compile-expr (expr env)
  (if (integer? expr)
    (compile-literal expr env)
    (if (boolean? expr)
      (compile-literal expr env)
      (if (symbol? expr)
        (cons env (list (list 'error "no variables supported")))
        (if (list? expr)
          (if (== expr '())
            (cons env (list (list 'error "Empty list")))
            (let ((op (car expr)))
              (if (== op '+)
                (if (== (length (cdr expr)) 2)
                  (compile-add (car (cdr expr)) (car (cdr (cdr expr))) env)
                  (cons env (list (list 'error "+ needs 2 args"))))
                (cons env (list (list 'error "Unknown operator"))))))
          (cons env (list (list 'error "Unknown type"))))))))

(print "Test 1: literal 42")
(let ((result (compile-expr 42 (make-env))))
  (print (cdr result)))

(print "Test 2: literal true")
(let ((result (compile-expr true (make-env))))
  (print (cdr result)))

(print "Test 3: addition (+ 1 2)")
(let ((result (compile-expr '(+ 1 2) (make-env))))
  (print (cdr result)))

(print "Test 4: nested (+ 5 (+ 2 3))")
(let ((result (compile-expr '(+ 5 (+ 2 3)) (make-env))))
  (print (cdr result)))
